services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: momo_backend
    ports:
      - "8080:8080"
    environment:
      # --- OVERRIDE LOCAL DEV (Wajib untuk menimpa .env Production) ---
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secretpassword
      - DB_NAME=momo_lms
      - DB_SSLMODE=disable
      
      # --- APP SETTINGS ---
      - SERVER_PORT=8080
      - AI_SERVICE_URL=https://ai-service-tunanetra.vercel.app
      - JWT_SECRET=cb2b654da996271e52beac0d93d45c423631b73e69d779ab46abf6b05008f91c
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
      - GIN_MODE=debug
      - APP_BASE_URL=http://localhost:8080
      - FE_VERIFY_REDIRECT_URL=http://localhost:3000/email-verified
      
      # --- BREVO SETTINGS (Diambil dari .env kamu) ---
      - BREVO_API_KEY=
      - BREVO_SENDER_EMAIL=dapinmail@gmail.com
      - BREVO_SENDER_NAME=Momo Platform
      
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:16-alpine
    container_name: momo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: momo_lms
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data: